### ISSUE TITLE
Zips missing?

### ISSUE THREAD

**Issue by yanismydj** [bgruber/zip2fips#3]
Love this project, thanks for heading it up.

I'm having trouble with some of the zips missing their corresponding Fips codes(especially ones from San Francisco, ie 94101, 94102-94109, etc).  Do you have any idea why they might be missing?  I'll see if I can find the missing data and submit a PR, but was wondering if you had any more ideas about this.

Thanks!

**Comment by willwest** [comment]
See #4 for explanation about why this is happening

**Comment by bgruber** [comment]
duplicate of #1
