### ISSUE TITLE
makejson.py doesn't read zipcty10 file (missing zip codes 93635+)

### ISSUE THREAD

**Issue by willwest** [bgruber/zip2fips#4]
The way it is written, this script will not read in the final zip file, `zipcty10`:

```
for i in range(1,10):
    zfile = open('zipctys/zipcty%d' % i)
    zfile.readline() # skip first line
```

The range produced will only include [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

This should be changed to `range(1, 11)` in order to include all zip files

**Comment by bgruber** [comment]
Duplicate of #1
