### ISSUE TITLE
Zips missing

### ISSUE THREAD

**Issue by gravitypersists** [bgruber/zip2fips#5]
PR fixing it is here: https://github.com/bgruber/zip2fips/pull/1 

This is a duplicate of https://github.com/bgruber/zip2fips/issues/4 but I'm opening a new one because, for some reason, the author is just closing issues without merging in the fixes. This is an open issue, and I hope by making it here it saves somebody some time if they come up against this.

**Comment by bgruber** [comment]
dupe of #1
